### ISSUE TITLE
Huggingface support

### ISSUE THREAD

**Issue by ghost** [alexa/bort#4]
Great work! Really looking forward to trying this out. Would it be possible to add Huggingface compatibility please? That would make it a lot easier to test with my application.

**Comment by adewynter** [comment]
Hi!

I've used Transformers for some experiments myself and I agree that it would be easier to add to some existing code, but I just don't have the bandwidth to undertake that ): So, unfortunately, that's not on our roadmap.

On the other hand, looks like there is an [open issue](https://github.com/huggingface/transformers/issues/8135) on their repo for that. It is quite possible that a PyTorch implementation of Bort will indeed be available in their awesome library sometime in the future.

Sorry about that!

-Adrian

**Comment by patrickvonplaten** [comment]
https://github.com/huggingface/transformers/pull/9112
