### ISSUE TITLE
Create pretraining data with multiprocessing not Implemented

### ISSUE THREAD

**Issue by 7AM7** [alexa/bort#7]
Hello @adewynter,
I noticed that you are using multiprocessing to create pretraining data script but your code is not completed I guess as mentioned on that line below:
- https://github.com/alexa/bort/blob/05adebf7a51ef03927947a24e08d20cd5609689e/create_pretraining_data.py#L588

Also here, What is worker_pool ?
- https://github.com/alexa/bort/blob/05adebf7a51ef03927947a24e08d20cd5609689e/create_pretraining_data.py#L248

So, Is your idea is to create a pool inside another pool? I mean pool with children of pools ?. Could you please give me more hints?

Thanks in advance

**Comment by adewynter** [comment]
Hi Ahmed! Good catch. This particular piece of code was not originally written by us (@daniel-perry probably can confirm here), and it corresponds to (i.e. it's almost the same thing as) an old version of [this](https://github.com/dmlc/gluon-nlp/blob/v0.9.x/scripts/bert/data/create_pretraining_data.py) script, with some adaptations for RoBERTa. 

It's quite likely that the missing multiprocessing implementation is the reason why [this](https://github.com/alexa/bort/issues/6) workaround is needed, and why the data preprocessing is so inefficient.

If it's causing you trouble, I'm fairly certain using an updated version of the dataloading script like the one I linked wouldn't make much of a difference. Indeed, you can use any script as long as it returns a RoBERTa-style embedding! :)

Hope this helps,

-Adrian
